// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Task struct {
	ID          int32
	Name        string
	Descritpion sql.NullString
	Status      string
}
